name: spyder
run-name: spyder
on:
  schedule:
    - cron: "25 6 * * *"  # 每天 UTC 6:25 執行 (台灣時間下午2:25)
  workflow_dispatch:       # 手動執行也可以

permissions:
  contents: write        

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10.6"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run static.py
        run: python static.py

      - name: Run api.py
        run: python api.py
        
      - name: Commit and Push results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add static.json api.csv
          git commit -m "Update from GitHub Actions" || echo "No changes"
          git push
