name: spyder
run-name: spyder

on:
  schedule:
    - cron: "0 6 * * *"   # 每天 00:00 (UTC) 執行
  workflow_dispatch:        # 手動觸發

jobs:
  run-spiders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10.6"
      
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run static.py
        run: python static.py

      - name: Run api.py
        run: python api.py

      - name: Commit output files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add static.json api.csv
          git commit -m "Update static.json and api.csv from workflow" || echo "No changes"
          git push
